
- type: entity
  id: BaseWeaponClothing
  abstract: true
  parent: BaseWeaponClothingOnlySounds
  components:
  - type: Clothing
    unequipDelay: 0.3
    equipDelay: 0.2


- type: entity
  id: BaseWeaponClothingOnlySounds
  abstract: true
  components:
  - type: Clothing
    unequipSound:
      path: /Audio/UFOS/Weapon/Handling/draw.ogg
    equipSound:
      path: /Audio/UFOS/Weapon/Handling/undraw.ogg

- type: entity
  id: BaseWeaponClothingOnlySoundsPistols
  abstract: true
  components:
  - type: Clothing
    unequipSound:
      path: /Audio/UFOS/Dress/mvt_strong_7.ogg
    equipSound:
      path: /Audio/UFOS/Dress/mvt_short_6.ogg

#WeaponSpeedMods

- type: entity
  id: BaseWeaponSpeedModifier
  abstract: true
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.9
  - type: HeldSpeedModifier
    mirrorClothingModifier: false
    walkModifier: 1
    sprintModifier: 0.83

- type: entity
  id: SpeedModifierBigGun
  abstract: true
  parent: BaseWeaponSpeedModifier
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.85
  - type: HeldSpeedModifier
    walkModifier: 1
    sprintModifier: 0.8

- type: entity
  id: SpeedModifierMediumGun
  abstract: true
  parent: BaseWeaponSpeedModifier
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.88
  - type: HeldSpeedModifier
    walkModifier: 1
    sprintModifier: 0.8

- type: entity
  id: SpeedModifierLightGun
  abstract: true
  parent: BaseWeaponSpeedModifier
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.99
  - type: HeldSpeedModifier
    walkModifier: 1
    sprintModifier: 0.9


#WeaponScopes
- type: entity
  id: LightScope
  abstract: true
  components:
  - type: Telescope
    divisor: 0.2
- type: entity
  id: x2Scope
  abstract: true
  components:
  - type: Telescope
    divisor: 0.2
- type: entity
  id: SniperScope
  abstract: true
  components:
  - type: Telescope
    divisor: 0.09