
- type: entity
  id: BaseWeaponClothing
  abstract: true
  parent: BaseWeaponClothingOnlySounds
  components:
  - type: Clothing
    unequipDelay: 0.3
    equipDelay: 0.2


- type: entity
  id: BaseWeaponClothingOnlySounds
  abstract: true
  components:
  - type: Clothing
    unequipSound:
      collection: MvtSlow
    equipSound:
      collection: MvtShort

- type: entity
  id: BaseWeaponClothingOnlySoundsPistols
  abstract: true
  components:
  - type: Clothing
    unequipSound:
      collection: MvtStrong
    equipSound:
      collection: MvtShort

#WeaponSpeedMods

- type: entity
  id: BaseWeaponSpeedModifier
  abstract: true
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.9
  - type: HeldSpeedModifier
    mirrorClothingModifier: false
    walkModifier: 1
    sprintModifier: 0.83

- type: entity
  id: SpeedModifierBigGun
  abstract: true
  parent: BaseWeaponSpeedModifier
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.85
  - type: HeldSpeedModifier
    walkModifier: 1
    sprintModifier: 0.8

- type: entity
  id: SpeedModifierMediumGun
  abstract: true
  parent: BaseWeaponSpeedModifier
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.88
  - type: HeldSpeedModifier
    walkModifier: 1
    sprintModifier: 0.8

- type: entity
  id: SpeedModifierLightGun
  abstract: true
  parent: BaseWeaponSpeedModifier
  components:
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 0.99
  - type: HeldSpeedModifier
    walkModifier: 1
    sprintModifier: 0.9


#WeaponScopes
- type: entity
  id: LightScope
  abstract: true
  components:
  - type: Telescope
    divisor: 0.2
- type: entity
  id: x2Scope
  abstract: true
  components:
  - type: Telescope
    divisor: 0.2
- type: entity
  id: SniperScope
  abstract: true
  components:
  - type: Telescope
    divisor: 0.09






- type: soundCollection
  id: MvtShort
  files:
    - /Audio/UFOS/Dress/mvt_short_1.ogg
    - /Audio/UFOS/Dress/mvt_short_2.ogg
    - /Audio/UFOS/Dress/mvt_short_3.ogg
    - /Audio/UFOS/Dress/mvt_short_4.ogg
    - /Audio/UFOS/Dress/mvt_short_5.ogg
    - /Audio/UFOS/Dress/mvt_short_6.ogg
    - /Audio/UFOS/Dress/mvt_short_7.ogg
    - /Audio/UFOS/Dress/mvt_short_8.ogg



- type: soundCollection
  id: MvtSlow
  files:
    - /Audio/UFOS/Dress/mvt_slow_1.ogg
    - /Audio/UFOS/Dress/mvt_slow_2.ogg
    - /Audio/UFOS/Dress/mvt_slow_3.ogg
    - /Audio/UFOS/Dress/mvt_slow_4.ogg
    - /Audio/UFOS/Dress/mvt_slow_5.ogg
    - /Audio/UFOS/Dress/mvt_slow_6.ogg
    - /Audio/UFOS/Dress/mvt_slow_7.ogg
    - /Audio/UFOS/Dress/mvt_slow_8.ogg


- type: soundCollection
  id: MvtStrong
  files:
    - /Audio/UFOS/Dress/mvt_strong_1.ogg
    - /Audio/UFOS/Dress/mvt_strong_2.ogg
    - /Audio/UFOS/Dress/mvt_strong_3.ogg
    - /Audio/UFOS/Dress/mvt_strong_4.ogg
    - /Audio/UFOS/Dress/mvt_strong_5.ogg
    - /Audio/UFOS/Dress/mvt_strong_6.ogg
    - /Audio/UFOS/Dress/mvt_strong_7.ogg
    - /Audio/UFOS/Dress/mvt_strong_8.ogg