
- type: entity
  id: BaseWeaponClothing
  parent: BaseWeaponClothingOnlySounds
  components:
  - type: Clothing
    unequipDelay: 0.3
    equipDelay: 0.2


- type: entity
  id: BaseWeaponClothingOnlySounds
  components:
  - type: Clothing
    unequipSound:
      path: /Audio/UFOS/Weapon/Handling/draw.ogg
    equipSound:
      path: /Audio/UFOS/Weapon/Handling/undraw.ogg

- type: entity
  id: BaseWeaponClothingOnlySoundsPistols
  components:
  - type: Clothing
    unequipSound:
      path: /Audio/UFOS/Dress/mvt_strong_7.ogg
    equipSound:
      path: /Audio/UFOS/Dress/mvt_short_6.ogg